[workspace]
resolver = "2"
members = ["crates/*"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
lto = 'thin'
opt-level = 2
overflow-checks = false
panic = 'unwind'
rpath = false

[profile.dev.package.backtrace]
opt-level = 3
